### ISSUE TITLE
Replace white highlight with red font in admin nav bar

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#1]
![screen shot 2016-06-08 at 5 30 13 pm](https://cloud.githubusercontent.com/assets/1813275/15913373/321287c0-2d9f-11e6-8fb2-17e56d67ed5b.png)
![screen shot 2016-06-08 at 5 32 58 pm](https://cloud.githubusercontent.com/assets/1813275/15913374/321608b4-2d9f-11e6-9456-aad926ee3057.png)

**Comment by siruguri** [comment]
Note - remove the red bar as well, underneath primary nav level
