### ISSUE TITLE
"add another" button should say "save"

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#100]
The user has to click the button to save the idea even if they don't want to add another idea,

![screen shot 2016-08-04 at 1 01 44 pm](https://cloud.githubusercontent.com/assets/1813275/17412712/bd99da3e-5a43-11e6-9313-21448a54c8d5.png)

**Comment by siruguri** [comment]
Doh. Of course :)

FIxed in future commit.
