### ISSUE TITLE
Ranking question in summary should sort ideas by highest ranked (top)

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#105]
![screen shot 2016-08-04 at 5 57 44 pm](https://cloud.githubusercontent.com/assets/1813275/17421128/106bd02c-5a6d-11e6-9890-c898cc18edf7.png)

**Comment by siruguri** [comment]
hmm, why did I think they need to be ordered as they were set in the survey question? Got that mixed up somehow, fixed it.
