### ISSUE TITLE
Budget questions fails to avg totals for ideas

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#106]
3 users answered the survey
1 user selected - $500.00 Realize a new ~ten hectare park system in East Fraserlands
2 users selected - $50.00 Develop additional policies and decision-making criteria to retain healthy, mature trees.

Yet the summary report came out as follows:
![screen shot 2016-08-04 at 6 33 35 pm](https://cloud.githubusercontent.com/assets/1813275/17421791/3ee71b50-5a72-11e6-8fed-b64c83361bad.png)

**Comment by siruguri** [comment]
Maybe we want to also calculate total spend across all participants; and then calculate the percentage contributed by each item as well.
