### ISSUE TITLE
Mobile budget pricing font is too large

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#111]
Should be 18 pt but appears to be 28 pt

The add to cart button should 7/12 (58.33%)

**Comment by Hallm13** [comment]
![img_1110](https://cloud.githubusercontent.com/assets/1813275/17441731/17f34c22-5af8-11e6-9256-1c774cd0be97.PNG)

**Comment by siruguri** [comment]
hmm ... I'm not so stoked abt that ... see below, if I keep 28px for just the amt font, reduce it to 18px for the Remove/Add language, and then make the width 75%.

You like?

![screen shot 2016-08-05 at 2 24 28 pm](https://cloud.githubusercontent.com/assets/40653/17451005/76bc3014-5b18-11e6-9a3a-f741ecca88d2.png)

**Comment by siruguri** [comment]
I can align the two parts, they are a bit off right now.

**Comment by Hallm13** [comment]
What is the browser width in your screenshot?

**Comment by siruguri** [comment]
1425px

Typed on a phone

**Comment by Hallm13** [comment]
1425px for mobile? That seems too large.
I'm concerned that 28 pt font won't fit on a 320 px width mobile browser.

**Comment by siruguri** [comment]
Oh,  sorry.  Didn't think to check on mobile. Will do.

Typed on a phone

**Comment by siruguri** [comment]
I think I have found a way to not reduce the font, but accommodate the two nicely even when the width is down to 350px (though it looks like most modern devices have widths of at least about 400px.)

Let's discuss.

**Comment by siruguri** [comment]
* Add margin-tops of -10px in both pro/con and budget
* Ensure margin-bottom is 40px
* Change font of button text to 16px (in budget)
