### ISSUE TITLE
Hover background fails to appear and unable to delete fields from non-idea radio

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#114]
![screen shot 2016-08-05 at 2 52 11 pm](https://cloud.githubusercontent.com/assets/1813275/17448896/586048b8-5b1c-11e6-9e32-f7273138d14c.png)

**Comment by siruguri** [comment]
i see the issue with the hover background failing ... by "unable to delete," you just mean that the X button won't show up, right?
