### ISSUE TITLE
What is the participation rate based off of?

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#115]
At the top of the summary, what is that number calculating?
![screen shot 2016-08-05 at 4 17 27 pm](https://cloud.githubusercontent.com/assets/1813275/17450843/3d27f3dc-5b28-11e6-9d01-3f8925776b91.png)

**Comment by siruguri** [comment]
Definitely implement "-- average number of screens answered, per respondent."

Maybe also get a sense of how this average breaks down, as percentage of respondents that answered 1, 2, ... N questions out of N.

**Comment by siruguri** [comment]
finished the must-have calculation - moving the other to an enhancement issue.
