### ISSUE TITLE
Inconsistent gutter spacing between idea cards in admin idea list

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#116]
![screen shot 2016-08-08 at 8 35 30 am](https://cloud.githubusercontent.com/assets/1813275/17481522/44fbc008-5d43-11e6-8ed0-5b2c6441971b.png)

**Comment by siruguri** [comment]
I think this is fixed in a build that will shortly be released (or might have been in the one this morning.) I think you mean this is in the admin-side ideas list page - if not, ( @Hallm13  ) lmk which participant page it is in and re-open.
