### ISSUE TITLE
Image should appear in idea cards

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#117]
Both admin and participant sides
![screen shot 2016-08-08 at 8 40 21 am](https://cloud.githubusercontent.com/assets/1813275/17481702/15ece73c-5d44-11e6-97b0-e075f6ddeb59.png)

**Comment by siruguri** [comment]
@Hallm13 - I didn't actually see the bug itself, but investigating it led to another problem I found that's actually a bug in Chrome. That might be related... or not. I'll close, but let's review at today's standup
