### ISSUE TITLE
Add a pro/con buttons should have 10px gutter to related idea card

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#119]
The pro/con buttons should be 10px away from the idea they are connected to and 20px away from the next idea. The same goes for the pros/cons once they have been saved. This helps illustrate which idea the pros/cons are connected to.

![img_1115](https://cloud.githubusercontent.com/assets/1813275/17497711/e67560c0-5d88-11e6-9251-16f9ca03a214.PNG)

**Comment by siruguri** [comment]
dupe of #121
