### ISSUE TITLE
Design of up/down arrows for questions in a survey

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#12]
@Hallm13 - which design shows the up/down arrows for ordering questions in a survey?

**Comment by Hallm13** [comment]
Are you asking about ordering ideas in a question or ordering questions in a survey? If it's questions in a survey, I still need to design that.

**Comment by Hallm13** [comment]
Up/down arrows should appear on hover:
https://docs.google.com/drawings/d/1D6SPWf_Ey_xauhYHH2uzzCB71Byo3rQGVTmlhOqFF7I/edit
