### ISSUE TITLE
Elements shift on button hover

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#124]
Pro/con and Budget questions shift idea cards and boxes up and down when hovering over buttons.
https://youtu.be/SzNBNGThj9Q

**Comment by siruguri** [comment]
@Hallm13 - browser version? I can't repro on Chrome 51 or FF 44.

**Comment by Hallm13** [comment]
Chrome Version 51.0.2704.103 (64-bit)

**Comment by siruguri** [comment]
aha, found it ... weird it didn't show up locally ...

**Comment by siruguri** [comment]
Note - Button borders needed to be made 2px on hover.
