### ISSUE TITLE
Mobile percentage widths for reports and admin

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#126]
![img_0097](https://cloud.githubusercontent.com/assets/1813275/17538648/f207fc74-5e6c-11e6-9613-cfd6bc8dee7a.PNG)

**Comment by Hallm13** [comment]
Add designs

**Comment by Hallm13** [comment]
@siruguri 
Admin is fine except for the toolbar. Here are the mobile percentages for the toolbar:
![iphone se - admin toolbar](https://cloud.githubusercontent.com/assets/1813275/17833874/bf8e8a20-66ef-11e6-88f5-88d2d6b7a5cb.png)

Summary is fine except for the ideas table. Table headings should be 16 for mobile instead of 18. Here's what the mobile percentages should be:
![iphone se - summary report](https://cloud.githubusercontent.com/assets/1813275/17833856/5104c614-66ef-11e6-8dce-9190e69ad545.png)

**Comment by siruguri** [comment]
- [ ] for the ideas summary tables, Table headings should be 16 for mobile instead of 18. 
- [ ] adjust first col to 25% for mobile in idea summaries
- [ ] adjust nav bar for admin create/list views

**Comment by siruguri** [comment]
I realized the column widths in the report tables are hard-coded to be print-able. They can't be set to modify based on browser width, because of the issue that they have to be copy-pastable from the desktop.

@Hallm13 - The easy solution is to make the first col for idea summaries 25% in all browser sizes ... works?

**Comment by siruguri** [comment]
Customize per report:

1. Pro/con - 15/15/70
1. Budget - 30/70 (combine avg spending with total cost in 1 col.)
1. All two col layouts otherwise are 25/75
