### ISSUE TITLE
Need a way to expand an idea to view an image and attachments

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#129]
Either click on the image to expand or click on the card to expand

Design (Same width as Idea Card)
![idea detail](https://cloud.githubusercontent.com/assets/1813275/17558807/7db09a78-5ee1-11e6-8270-f20d16bfd8f0.png)

**Comment by siruguri** [comment]
* Trigger Read More link even if description is short, as long as there are attachments.
* On triggering read more, make image span width of idea card.
