### ISSUE TITLE
Implement idea w/pics and attachments

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#13]
https://docs.google.com/presentation/d/1bMFnUz_5PilDtymvq9SYAc03AAKYebT0dMIBfzJDV8I/edit#slide=id.g1195d59c95_0_0

https://docs.google.com/drawings/d/1H_6HyAAHLPzesKpY80fPfk1YMrB9iobdYmKs2nqaNNI/edit

**Comment by Hallm13** [comment]
Include read more box with links

**Comment by siruguri** [comment]
#6 has some other details; but it's closed as duplicate of this.
