### ISSUE TITLE
Unable to delete example field from non-idea field question create (staging/prod)

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#135]
![screen shot 2016-08-12 at 12 41 57 pm](https://cloud.githubusercontent.com/assets/1813275/17631565/43719240-608a-11e6-9f45-c46a87e935e7.png)

**Comment by siruguri** [comment]
Do you mean, delete the "Example Entry"? You can't delete it - it's there
to fill up the "min 3" - but it doesn't actually populate on the particip
side.

I can delete the ones I create ... like "Email" in your example - can you
delete them?
