### ISSUE TITLE
Update report styling

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#137]
The create survey page still needs styling for the summary that appears there, the survey list needs the participation rate to be a percentage, and the participation rate should also be a percentage on the summary report.
![screen shot 2016-08-12 at 3 07 48 pm](https://cloud.githubusercontent.com/assets/1813275/17635738/c3ce5acc-609e-11e6-85f4-944a826d90b9.png)
![screen shot 2016-08-12 at 3 07 57 pm](https://cloud.githubusercontent.com/assets/1813275/17635739/c3ced66e-609e-11e6-95ce-d1934a5c6081.png)
![screen shot 2016-08-12 at 3 08 18 pm](https://cloud.githubusercontent.com/assets/1813275/17635740/c3cf3e60-609e-11e6-816c-1ef315b57bdc.png)

**Comment by Hallm13** [comment]
Also missing unique participants and participation rate per question in the summary report
![screen shot 2016-08-12 at 5 21 15 pm](https://cloud.githubusercontent.com/assets/1813275/17638681/574974d2-60b1-11e6-9631-8351d9d527eb.png)

**Comment by Hallm13** [comment]
Ranking should start at "1" instead of "0" in reports

![screen shot 2016-08-12 at 5 27 12 pm](https://cloud.githubusercontent.com/assets/1813275/17638778/20da74ea-60b2-11e6-988d-1fe2cb71d034.png)

**Comment by siruguri** [comment]
@Hallm13  - Could you point me to the mockup that shows the "survey summary styling in the create survey page"?

**Comment by Hallm13** [comment]
@siruguri 

![survey create](https://cloud.githubusercontent.com/assets/1813275/17645253/c0b4e8d4-6165-11e6-92b0-bbad95e04f6f.png)

**Comment by siruguri** [comment]
- [X] The create survey page still needs styling for the summary that appears there
- [X] the survey list needs the participation rate to be a percentage, and 
- [X] the participation rate should also be a percentage on the summary report
- [ ] rates within each question's report
- [ ] start all ranks at 1, not 0

**Comment by siruguri** [comment]
@Hallm13  - can you check the above 5 items are the ones that needed a fix?

**Comment by Hallm13** [comment]
@siruguri As long as all of the reports are calculating right, then that's all of the items

**Comment by Hallm13** [comment]
Participation rate on the survey list page is calculating incorrectly
![screen shot 2016-08-15 at 7 11 29 pm](https://cloud.githubusercontent.com/assets/1813275/17683845/240185e8-631c-11e6-85d1-189ad21918a4.png)

**Comment by Hallm13** [comment]
@siruguri 
Participation rate should be the average of all the participation rates for all of the individual questions.

Example - "Cycling Priorities" survey in prod
Question 1 = 100% participation rate
Q2 = 90%
Q3 = 90%
Q4 = 90%
Q5 = 60%
Q6 = 10%

The overall survey participation rate should be 73.33%

**Comment by Hallm13** [comment]
Budget question is listing the idea cost incorrectly 

The cost numbers in this example should be: 
$100
$50
$50

![screen shot 2016-08-15 at 7 25 07 pm](https://cloud.githubusercontent.com/assets/1813275/17684068/28a109f0-631e-11e6-8b82-e06ab102d5fb.png)

**Comment by siruguri** [comment]
I've definitely not written the survey participation rate that way... Will
change.

Typed on a phone

**Comment by siruguri** [comment]
Found that budget question bug too ...
