### ISSUE TITLE
Questions have descriptions?

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#14]
https://docs.google.com/drawings/d/1gX2CcW-Z8Y-tFs4I8ydq0_WfiZfMBORo9lMVLLTWZ54/edit

I couldn't find the design that shows where descriptions are added to questions. You had mentioned that when we were discussing the card design for questions in a survey.

**Comment by Hallm13** [comment]
The description should be edited/added within the preview. So, the ranking question preview should include a default description that says, "Please rank the following in order or importance." Then the admin can just leave that description or edit it within the preview box.

**Comment by siruguri** [comment]
Ah, ok - I have two fields, a description and a "prompt" and it seems like the latter is what you meant by "description." Is that right?

**Comment by Hallm13** [comment]
For the fields question, there should be a description and sort of like helper text that actually goes in the field.

Ex. description:

Fill fill out the following address information

Ex. prompt/helper text:

Street address, zip code, etc

I suppose it would make more sense to call the description the prompt and the prompt helper text.

**Comment by siruguri** [comment]
So the prompt is just a fixed text, right? For example, for [the fields question design](https://drive.google.com/drive/u/1/folders/0B4i5Ynx7vu_nQk50YjJicmdOYVE), the prompt shows in the Preview section but it's not editable. Did I understand that correctly?

**Comment by Hallm13** [comment]
Both the prompt and helper text should be editable by the admin in the preview. That way they can create their own demographic questions.

**Comment by siruguri** [comment]
duplicate of #33
