### ISSUE TITLE
Character minimums should be shorter - allow one word responses

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#141]

**Comment by siruguri** [comment]
Make all the minimums 1?

Typed on a phone

**Comment by Hallm13** [comment]
Yeah, 1 is good.

**Comment by siruguri** [comment]
And everything is 1, right? Intros, titles, descriptions, thank you note?

**Comment by Hallm13** [comment]
Right, except descriptions shouldn't have a minimum.
