### ISSUE TITLE
Add an idea from survey is broken (prod/staging)

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#142]
Doesn't save when use clicks save

**Comment by siruguri** [comment]
@Hallm13 - you mean, "Add an idea from survey **question**" is broken? I can't repro that...

**Comment by siruguri** [comment]
clarification - for participant... not for admin.

**Comment by siruguri** [comment]
also, right now, it's broken because the `card_image_url` is not being recorded as an attribute.

**Comment by siruguri** [comment]
works on staging - didn't want to mess up prod data...

![screen shot 2016-08-15 at 3 11 49 pm](https://cloud.githubusercontent.com/assets/40653/17681452/a7f807c2-62fa-11e6-9dc2-a35af0b268bd.png)
