### ISSUE TITLE
Update pro/con styling

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#143]
- [x] Add a con border hover should be #C54943 instead of #409599

- [x] Pros and Cons columns should have heading once a pro or con is added

- [x] Save button font color and border hover should be #4183D7

Current
![screen shot 2016-08-13 at 3 30 34 pm](https://cloud.githubusercontent.com/assets/1813275/17645440/d40266d6-616b-11e6-991e-9bee97ba0431.png)

Design
![screen shot 2016-08-13 at 3 34 20 pm](https://cloud.githubusercontent.com/assets/1813275/17645441/e2083d32-616b-11e6-80a1-a738ee07704b.png)

**Comment by siruguri** [comment]
@Hallm13 - you mean, the save button for new ideas for particip? I think the design is that the background is white, font and hover are blue (and I have blue = #B9E0F1? 

https://projects.invisionapp.com/share/KY68U9I87#/screens/173366710

**Comment by siruguri** [comment]
@Hallm13 - if there are only pros (cons) should there only be the "Pros" ("Cons") heading - or both?

**Comment by Hallm13** [comment]
@siruguri There is a save button for saving a pro/con on the participant side
![screen shot 2016-08-15 at 5 25 53 pm](https://cloud.githubusercontent.com/assets/1813275/17681818/835a383c-630d-11e6-9995-98027474ca4a.png)

**Comment by Hallm13** [comment]
@siruguri There should be both headings even if there are only cons/pros
