### ISSUE TITLE
Read more fails to expand idea card on mobile

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#147]
Either the "read more" does not appear in the card or if it does appear, when the user clicks on it the window doesn't expand or only expands a little.
![img_1149](https://cloud.githubusercontent.com/assets/1813275/17794046/c61a74e6-6571-11e6-8a69-7af052babca3.PNG)

**Comment by siruguri** [comment]
Need the basics of the button to be used in place of the current Read More/Less design - something like font size, background color, any hover behaviors...

**Comment by siruguri** [comment]
Use design in https://github.com/Hallm13/ideamapr/issues/157
