### ISSUE TITLE
Fixed footer banner w/ client name 

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#148]

**Comment by Hallm13** [comment]
Need design for this along with terms and condition #51

**Comment by Hallm13** [comment]
@siruguri 
Maybe this shouldn't be fixed position. That may be take up too much real estate. Here's my mockup
![footer](https://cloud.githubusercontent.com/assets/1813275/17832229/5a780a20-66c3-11e6-97b2-c31772f31f6e.png)

**Comment by siruguri** [comment]
@Hallm13 - what's the space between "Conditions" and "Privacy"?

can we have those two lines stack instead? Or be separated by say " | " without adding arbitrary spacing between them?

**Comment by Hallm13** [comment]
Yes, they can be separated with a "|".

**Comment by siruguri** [comment]
@Hallm13 - what are the target links for TOS and privacy policy?

**Comment by siruguri** [comment]
- [ ] Need to put it in the public facing template

**Comment by siruguri** [comment]
- [ ] Make lines stack in mobile - remain text centered
