### ISSUE TITLE
Admin ranking control for non-idea radio questions

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#15]
https://docs.google.com/drawings/d/14xRWbYBNF_EMXAZm6EO-VjygDDNgYiR4bzlizYI5sLo/edit

I couldn't figure out which design shows how you envision adding the ranking and delete controls, to a non-idea radio question.

In the above design, there doesn't seem to be enough space to put in the chevrons on the left.

**Comment by Hallm13** [comment]
![field question create](https://cloud.githubusercontent.com/assets/1813275/16364356/e042dd54-3baa-11e6-97d8-7caf6445dbfe.png)
![x](https://cloud.githubusercontent.com/assets/1813275/16364367/03be15be-3bab-11e6-92b9-74735142d80e.png)
![path 5](https://cloud.githubusercontent.com/assets/1813275/16364368/0714e300-3bab-11e6-947a-7da6947bbb0a.png)

**Comment by siruguri** [comment]
Basic design is done but the admin ranking chevrons need to be updated cf #22 - closing this as duplicate/implemented.
