### ISSUE TITLE
Map-based feedback

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#150]
Map of all ideas
- drop a pin to create an idea
- draw a routes to create an idea

Ideas
- can display map as card cover
- admins can add a location or route to an idea

**Comment by Hallm13** [comment]
First enter address info for ideas
Use google api to confirm that it's a usable address
Figure out how to visualize data later

**Comment by siruguri** [comment]
Small version

* First enter address info for ideas
