### ISSUE TITLE
"X" for attachment delete is misaligned

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#152]
![screen shot 2016-08-19 at 10 44 21 am](https://cloud.githubusercontent.com/assets/1813275/17815452/ff82a64e-65f9-11e6-8be2-e10e7c1baba9.png)

**Comment by siruguri** [comment]
also I padded that gray area a bit so the mouse is not accidentally on the wrong X.

![screen shot 2016-08-22 at 11 14 47 am](https://cloud.githubusercontent.com/assets/40653/17865998/b9f252ca-6859-11e6-8623-39561d1870b1.png)
