### ISSUE TITLE
Fraud alert

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#153]
Track when a user is answering a survey multiple times and create the ability to exclude those response from the report.

**Comment by Hallm13** [comment]
Maybe a captcha

Track IP addresses to see a pattern
- see a bunch of responses from the same ip addresses
- manually remove responses from database or filtering

**Comment by siruguri** [comment]
Small version for 1.6:

* Capture IP address for survey responses, so we can filter based on this later.
