### ISSUE TITLE
Allow paragraphs in description fields

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#158]
If there are more than two newlines in sequence, anywhere in the field, they will be collapsed into a single HTML paragraph space.

- [x] idea intro
- [x] question prompt
- [x] survey intro
- [x] survey thank you

**Comment by siruguri** [comment]
@Hallm13 - do you anticipate question prompts getting so large, they need to be broken into paragraphs? That seems like a bad survey design choice...

**Comment by Hallm13** [comment]
Budget question may require that long of a prompt.
