### ISSUE TITLE
Budget question: add cart toggles with "remove cart"

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#16]
Could you point me to the design for Remove From Cart in the budget question?

**Comment by Hallm13** [comment]
https://docs.google.com/drawings/d/1gZf0aL5h4Kol4Vlz1Nb3r_RAQUj9FSLiUfqgKPC2u5k/edit

**Comment by siruguri** [comment]
Can participants not add multiple quantities of the same item? This design allows only for 0 or 1 items.

**Comment by siruguri** [comment]
Discussed in standup - it's either 0 or 1 item.
