### ISSUE TITLE
Unable to edit non-idea field helper text

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#160]
The helper text just says whatever the prompt text is and doesn't reflect changes.
![screen shot 2016-09-03 at 8 49 16 am](https://cloud.githubusercontent.com/assets/1813275/18225235/a40308c0-71b3-11e6-82c8-d9c4450b2e80.png)

**Comment by siruguri** [comment]
can you post a video? I am not able to repro at least in the way in which I conceptualize this feature:

https://youtu.be/a3YYEViobyY

**Comment by siruguri** [comment]
- [ ] Make text field into text area
- [ ] Have input field span maybe 100% of the field card
