### ISSUE TITLE
Design for thank you page links

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#162]

**Comment by Hallm13** [comment]
@siruguri Here are the designs I owe you. Can we make it so that the link appears as a button and the admin adds a link and text for the button? Also, can the button not appear if there is no link added?


Admin side
![screen shot 2016-09-12 at 7 01 18 pm](https://cloud.githubusercontent.com/assets/1813275/18457074/6fb3e174-791b-11e6-887b-9d05e5050723.png)

Participant side
![thank you](https://cloud.githubusercontent.com/assets/1813275/18457073/6fb39d68-791b-11e6-9178-75121a81d410.png)

**Comment by siruguri** [comment]
Can we make it be just one button? I don't want to increase the complexity
with being able to add/delete etc... either it's there, or not there.

**Comment by Hallm13** [comment]
Right, it would just be one button. Admins would not be able to add or delete buttons. Either they input a link and the button appears or they don't fill out that field and there's no button.

**Comment by siruguri** [comment]
I don't think there's a way to add a link here ... in the admin side ... I'll assume you meant to have another box that says Thank You Button Link

**Comment by Hallm13** [comment]
Right, I forgot that box. Should be just below the other text box.
