### ISSUE TITLE
Adding a thank you page link changes the footer name to the link

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#165]
![screen shot 2016-09-15 at 3 21 36 pm](https://cloud.githubusercontent.com/assets/1813275/18566127/3d10ddf0-7b58-11e6-9436-421a01854ad1.png)

**Comment by siruguri** [comment]
Dynos need both settings - CITY_NAME and CITY_SITE_LINK - for it to show up in the footer.
