### ISSUE TITLE
Track sessions even after quitting browsers (1st priority)

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#17]
Survey reports count a unique user as a participant who views the survey even if they do not answer a question. That user is only counted once even if they quite their browser and return to the survey later.

**Comment by siruguri** [comment]
#32 will implement the second requirement above: "That user is only counted once even if they quite their browser and return to the survey later."

However, counting "views" of participants who don't answer anything is left as a future enhancement (#31)

Closing this issue as duplicated.
