### ISSUE TITLE
Idea select dropdown

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#19]

**Comment by siruguri** [comment]
can you link to the invision previews we just looked at?

**Comment by Hallm13** [comment]
https://docs.google.com/drawings/d/1v3U-vu5mCVtZ7u8Fol-m0ju5wDXMWhrBBh8Yq3pOYzo/edit

**Comment by siruguri** [comment]
* Use idea card design in popup as well
* confirm ordering of ideas is most-recent-first
* Anchor bottom of popup to the add idea/question button
* Make the popup fixed height, and add an internal scroll bar
* Put add buttons on left, similar to ranking buttons placement
* try to fix the overlay appearance
