### ISSUE TITLE
Add white space to 2nd level admin nav bar

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#2]
- add red font (#c54943)
- change black font to #676d73
- move text underline

![screen shot 2016-06-08 at 5 36 04 pm](https://cloud.githubusercontent.com/assets/1813275/15913445/ae23e7d2-2d9f-11e6-8912-38d5bfa2b1f9.png)
![screen shot 2016-06-08 at 5 36 35 pm](https://cloud.githubusercontent.com/assets/1813275/15913446/ae248052-2d9f-11e6-9643-8c349b9ce6d1.png)

**Comment by siruguri** [comment]
Can we confirm the following:

* One of the three items in the first level is always red (it's what was last clicked.)
* When you click on one of the first-level items, the second-level item is "X List", where X is Questions, Ideas, or Surveys
* The possible values after the "X List" in the 2nd-level are "X Create" and "X Edit"

**Comment by Hallm13** [comment]
1. Correct - red text in the first level nav bar highlights whether the admin is working on ideas, questions, or surveys
2. Yes, exactly right
3. The only possible value is "X Create". Create and edit should be the same page and that page is called "Create". This applies to idea, questions, and surveys.
