### ISSUE TITLE
Prompt text in text boxes for survey creation

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#24]
Could you link the mockups that show what text is in the boxes for survey creation?

I found a couple of drawings in https://drive.google.com/drive/u/0/folders/0B4i5Ynx7vu_nSFNDMnF0RTlQRm8 that say "Survey Create" but these designs look so old I'm not sure if I should use them.

**Comment by Hallm13** [comment]
Here's the latest designs:
https://drive.google.com/open?id=0B4i5Ynx7vu_nVnd5Q2JxbFlCa1E
