### ISSUE TITLE
Budget question create design

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#29]
The text for the box where the budget (total amount available) should be entered isn't in the designs -- I think [Final Admin](https://drive.google.com/drive/u/1/folders/0B4i5Ynx7vu_nbUtwSDJOcDZxTHc) doesn't have Budget question as a mockup?

**Comment by Hallm13** [comment]
Here is the design for that: 
https://drive.google.com/open?id=0B4i5Ynx7vu_nUHNFUkpSdHhTYTA

Admins can enter the total budget available in the preview along with the cost of each idea, question description, etc.

**Comment by siruguri** [comment]
Hmm, can we implement it for now so that there is a separate field for entering the budget, and that value is reflected in the preview, rather than have the preview directly editable?

**Comment by Hallm13** [comment]
Would that mean that the preview is not editable for any question type? Field and radio non-idea questions also require an editable preview.

**Comment by siruguri** [comment]
Only the question prompt will be inserted from above into the preview
