### ISSUE TITLE
Ranking ideas need design alignment

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#30]
The idea rank should be shown correctly.

@Hallm13 - where is the design for this? [The latest version](https://drive.google.com/file/d/0B4i5Ynx7vu_nZ2xhZGhpYTdJTEE/view) doesn't show the idea's rank in the preview screen; I couldn't find ranking qns in the participants folder.

**Comment by Hallm13** [comment]
Here's the latest:
https://drive.google.com/open?id=0B4i5Ynx7vu_nTXJFM3JCdzlEVG8
