### ISSUE TITLE
Combine report data into look-and-feel for reports

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#36]

**Comment by siruguri** [comment]
https://docs.google.com/document/d/16L2d-w9LCJhfesPa5VNg5W0NZSjxWujSKES4hqdTTrs/edit

**Comment by Hallm13** [comment]
We don't need to include "total views" since we can track separately via google analytics.

**Comment by siruguri** [comment]
Notes on calculation specifics

### Ranking questions
* Ideas are shown in order of assignment in the question; the average rank across all answers even from incomplete surveys is shown.
