### ISSUE TITLE
Implement "Add an idea" screens

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#38]

**Comment by siruguri** [comment]
https://invis.io/KY68U9I87#/173366710_Add_Idea

Click on "save" at the bottom of the screen.

**Comment by siruguri** [comment]
@Hallm13 - as just noted in email, this screen needs an "Add Another Idea" button to distinguish it from "Save Response" - only the latter sends the response to the server.

**Comment by Hallm13** [comment]
Couldn't the user just click "next" when they want to go to the next question? The "save" button should save their response to the server and bring up a new field to add another idea.

**Comment by siruguri** [comment]
I would rather have a single save per question... the fewer requests to the
server, the better.

the next button will indeed move on but the answer is still unsaved to the
server.

alternatively, finish on the final screen can do one final save for
anything not saved already.

the confusion is that for some questions, you may not want to save on
hitting next - ranking for example.

**Comment by Hallm13** [comment]
I think it would be confusing to have a save button not mean that it will save to the server. Pro/Con questions will also need save buttons for each pro/con unless the next button will save the whole page, which may also be confusing and users could potentially lose a lot of work if they created multiple pro/cons.

Saving on the next button should be fine for ranking as long as the user clicks on an arrow and ranks something.

**Comment by siruguri** [comment]
Ok,  maybe we don't need a separate Save button at all then... Might have
been my misunderstanding... Let's resolve at stand up today.

Typed on a phone
