### ISSUE TITLE
Align vertical/horizontal spaces with design

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#45]

**Comment by Hallm13** [comment]
Also include fonts - smallest font is set by the browser and then pick the next two larger fonts relative to that font size.

**Comment by Hallm13** [comment]
![ideamapr style guide](https://cloud.githubusercontent.com/assets/1813275/16998208/090a9976-4e7e-11e6-849b-9c3ffd2d5a94.png)
![heirarchy of type](https://cloud.githubusercontent.com/assets/1813275/16998260/3d7766da-4e7e-11e6-86a5-1cd935dc40c8.png)

@siruguri Does this work for you?

**Comment by siruguri** [comment]
@Hallm13 - looking pretty good - I will add questions here if I think of any.

**Comment by siruguri** [comment]
@matt - there's something I don't understand - you have a first and a second "target" that have widths of 3/4ths and 2/3rd respectively. What is a first and second target? In the screenshots here, it looks like all the cards are second target (66%) but what's the "preview" then, which is first target?

What level - first or second - would the elements on the admin side be?

Can we instead say everything is 75% (previews, form entry boxes), except buttons which are 66%?

**Comment by Hallm13** [comment]
The preview has to be a little bit bigger than the other elements, so that they can fit inside of the preview. The "targets" are just labels to differentiate the different sizes.
