### ISSUE TITLE
Create ability to attach pictures, pdfs, and docs to ideas

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#6]

**Comment by siruguri** [comment]
Can you describe here how the attachments would be used? Would each for example be a separate screen in the participant view, or be a list of links on one of the screens?

**Comment by Hallm13** [comment]
Can we do previews for docs, pdfs, and csvs?
https://docs.google.com/drawings/d/1H_6HyAAHLPzesKpY80fPfk1YMrB9iobdYmKs2nqaNNI/edit

**Comment by siruguri** [comment]
* Previews for docs/csvs would be hard to let's postpone that.
