### ISSUE TITLE
Error message still displays when issue is resolved

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#62]
1. User attempts to save a question that only has a description and no title
2. Error message appears - yup, this works as intended so far
3. User adds a title and saves the question
4. Error message still displays on the question list page even though the error is resolved

![screen shot 2016-08-01 at 7 56 27 pm](https://cloud.githubusercontent.com/assets/1813275/17313566/51913de6-5822-11e6-9a91-f94f857ca948.png)

**Comment by siruguri** [comment]
Did you mean, "attempts to save an _idea_"?
