### ISSUE TITLE
Question type dropdown does not work until the question is saved

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#64]
The expected behavior is that the admin should be able to cycle through the question types and add ideas before saving the question.

![screen shot 2016-08-01 at 8 03 21 pm](https://cloud.githubusercontent.com/assets/1813275/17313665/342526c2-5823-11e6-817d-439681170726.png)

**Comment by siruguri** [comment]
hmm I don't quite get this - if you change the type, the preview does change.

https://youtu.be/FaM-PduPTiU

**Comment by Hallm13** [comment]
Yeah, it's working now but wasn't changing last night.

**Comment by siruguri** [comment]
hmm... will close for now, let me know if you see it again and re-open.
