### ISSUE TITLE
The minus sign in the down ranking button is misaligned

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#66]
It should appear in the middle of the icon instead of at the top of the icon
![screen shot 2016-08-01 at 8 08 41 pm](https://cloud.githubusercontent.com/assets/1813275/17313726/e11e6f64-5823-11e6-9148-1d42d399105e.png)

**Comment by siruguri** [comment]
are you seeing this only in the admin view, or in the participant view as well?
