### ISSUE TITLE
Publishing survey erases questions

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#75]
1. add questions to a survey in draft mode
2. publish the survey
3. edit the survey or preview the survey to see that all of the questions are gone

**Comment by siruguri** [comment]
I can't repro - https://ideamapr-staging.herokuapp.com/surveys/2/edit?locale=en is published, but I can see its assigned questions. Is that not what you meant?

**Comment by siruguri** [comment]
Can't repro - will close for now.
