### ISSUE TITLE
Changes to summary reports

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#77]
Increase spacing between idea lines. Also increase spacing below "Ranking Averages".
![screen shot 2016-08-03 at 12 51 45 pm](https://cloud.githubusercontent.com/assets/1813275/17376012/3900de1e-5979-11e6-9664-e0cd5d4f7285.png)

Numbers on the left should be green and the numbers on the right should be red
![screen shot 2016-08-03 at 1 09 40 pm](https://cloud.githubusercontent.com/assets/1813275/17376606/f0455e90-597b-11e6-9b84-f709f230fa70.png)
![screen shot 2016-08-03 at 1 10 30 pm](https://cloud.githubusercontent.com/assets/1813275/17376605/f043b838-597b-11e6-97a8-d3f08a97f2d9.png)

"Completed this question" and "participation rate" should be center aligned

Radio Idea question should have ideas on the left instead of the right. Also, it displays "Selected at Top" for some reason.

![screen shot 2016-08-03 at 2 42 16 pm](https://cloud.githubusercontent.com/assets/1813275/17379607/cecea1ce-5988-11e6-8817-f2e68467119d.png)

**Comment by siruguri** [comment]
5px between rows (idea lines), and 20px between table headers and first row?

**Comment by Hallm13** [comment]
Can we try 10px for both the idea lines and the table headers?

**Comment by siruguri** [comment]
* Completed this question" and "participation rate" should be center aligned - make the two columns quarter each and center align the text inside.

**Comment by siruguri** [comment]
- [x] Numbers on the left should be green and the numbers on the right should be red
- [x] "Completed this question" and "participation rate" should be center aligned
- [x] Radio Idea question should have ideas on the left instead of the right. Also, it displays "Selected at Top" for some reason.
