### ISSUE TITLE
Broken links on second level admin nav

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#87]
Clicking on questions or create questions ends in a 404. This also happens with the surveys and ideas columns.

![screen shot 2016-08-04 at 10 41 47 am](https://cloud.githubusercontent.com/assets/1813275/17408273/27103260-5a30-11e6-907b-e66dc63778c5.png)

**Comment by siruguri** [comment]
come to think of it, those shouldn't be links at all, in the 2nd level nav, yes?

**Comment by Hallm13** [comment]
Yeah, the either need to link somewhere or just not be links. I'd good with either one.

**Comment by siruguri** [comment]
got it - I'll just remove the links.
