### ISSUE TITLE
Apply participant nav bar styling

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#90]
Nav bar text should be in #676D73 for "previous" and question title.
"Next" button text should be in #FFFFFF
"Previous" button color should be #F0F1F2

Current
![screen shot 2016-08-04 at 12 16 07 pm](https://cloud.githubusercontent.com/assets/1813275/17411379/ddb7d484-5a3d-11e6-9dac-4b76c3b5a42f.png)

Design
![screen shot 2016-08-04 at 12 20 24 pm](https://cloud.githubusercontent.com/assets/1813275/17411378/ddb32de4-5a3d-11e6-985a-ada06d5f37bb.png)

**Comment by Hallm13** [comment]
Previous and Next button widths are still too small.
Next and Previous text should be 18pt regular 
Nav bar text should be in #676D73 for "previous" and question title.

Current
![screen shot 2016-08-11 at 9 30 32 am](https://cloud.githubusercontent.com/assets/1813275/17592083/85566bac-5fa6-11e6-8af2-d8f77338de7d.png)

Design
![screen shot 2016-08-11 at 9 30 19 am](https://cloud.githubusercontent.com/assets/1813275/17592092/8c313696-5fa6-11e6-905e-cb52eec797d7.png)

**Comment by siruguri** [comment]
@Hallm13  - What's the intended width of the survey screen text? Is it 75%?

**Comment by siruguri** [comment]
Reference: 238 + 356

**Comment by siruguri** [comment]
- [X] Previous and Next button widths are still too small. - **sameer: I think I fixed this, will push our shortly**
- [ ] Next and Previous text should be 18pt regular 
- [X] Nav bar text should be in #676D73 for "previous" and question title.
- [ ] Width of screen beneath navbar is correct.

**Comment by Hallm13** [comment]
@siruguri Do you mean the prompt text beneath the nav bar? Is that the screen text?

**Comment by siruguri** [comment]
good point - actually I meant what's beneath the prompt, but yeah, what should the width of the prompt be, if it's not centered within the same box as the ideas/fields themselves?

**Comment by siruguri** [comment]
Also, I'm not sure I am figuring out the mobile behavior for the navbar correctly - let's talk.

**Comment by Hallm13** [comment]
@siruguri do you want to do a hangout right now?
