### ISSUE TITLE
Maximum height for idea card?

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#93]
What is the maximum height for the idea card? It seems like some cards are much bigger than others and we may need to standardize this more.

![screen shot 2016-08-04 at 12 39 47 pm](https://cloud.githubusercontent.com/assets/1813275/17412138/c418d638-5a40-11e6-9bee-f752fa848e44.png)
![screen shot 2016-08-04 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/1813275/17412139/c41a54f4-5a40-11e6-837a-85d1d2177098.png)

**Comment by siruguri** [comment]
There's a minimum height, and then it stretches a bit when there's a 3rd line ... we could have a fixed height for when the text is collapsed, and only stretch it when the text is extended ... does that work?

**Comment by siruguri** [comment]
148px is the expected min height of the card - this might have to be re-styled a bit.

**Comment by siruguri** [comment]
Moved where the `min-height` is applied.
