### ISSUE TITLE
"Remove from cart" button should be in #C54943

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#95]
Current
![screen shot 2016-08-04 at 12 44 33 pm](https://cloud.githubusercontent.com/assets/1813275/17412236/51c0466a-5a41-11e6-9f1f-952fa781e609.png)

Design
![screen shot 2016-08-04 at 12 45 42 pm](https://cloud.githubusercontent.com/assets/1813275/17412254/69e767f0-5a41-11e6-9220-fed94041c61d.png)

**Comment by siruguri** [comment]
Also noted that the hover border on the button, and the color in the adjacent spent amount shd toggle.
