### ISSUE TITLE
Apply unranked styling to ranking question

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#98]
When a user first views a ranking question it should not have ranking numbers. That way the user must rank an idea to answer the question. As soon as the user ranks an idea than the numbers will appear.

Also, the ranking numbers seem to be misaligned. they should be centered.

Current
![screen shot 2016-08-04 at 12 51 38 pm](https://cloud.githubusercontent.com/assets/1813275/17412470/76fa795e-5a42-11e6-9992-bfcd70c02e80.png)

Design
https://youtu.be/D3a0TscoIe4

**Comment by siruguri** [comment]
@Hallm13 I'm not sure I see the misalignment ... it's centered, as far as the browser concerned, that could be a visual illusion produced by the way this font draws the '1'. Or something that's browser-specific.

Yeah, the unranked behavior never got implemented, have to work on that.
